[phases.setup]
nixPkgs = ['python310', 'gcc']

[phases.install]
cmds = [
'python3 -m venv venv',
'. venv/bin/activate',
'pip install --upgrade pip',
'pip install -r requirements.txt'
]

[start]
cmd = "venv/bin/python app.py"
